language: python
python:
    - 2.7
    - 3.5

install:
    - pip install --upgrade pytest codecov coverage
    - pip install .

script:
    - coverage run --source scache -m py.test

after_success:
    - codecov
